[[redirects]]
  from = "/todo"
  to = "https://www.awskjh.p-e.kr/todo"
  status = 200
  force = true
  
[[redirects]]
  from = "/api/*"
  to = "https://api.openweathermap.org/data/2.5/group:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200